### ISSUE TITLE
Pets:

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#107]
I did it: but when i do it
the pet die already?
and water of life doesnt work to bring back the pets
how can i fix and which files should i look in to start off
[img]https://i.imgur.com/xnFyPkr.png[/img]

**Comment by ronancpl** [comment]
If nothing happens when using Water of Life, it is not coded yet. To start, one must know which packet the client is sending to server when requiring some action from the server (client wants server to make an action for "Water of Life"). You must get the opcode to start implementing on the right handler.

Enable USE_DEBUG_SHOW_RCVD_PACKET, it will start printing packets that must be handled on cmd, in decimal integer format. Get the opcode you receive when using WoL, pass to hexadecimal, and you get the right RecvOpcode to use. Open the handler file that gets triggered with this opcode.

Inside the file, implement a way to use the item you want to take the effect.

As a matter of fact, the handler file UseCashItemHandler will handle WoL. All you have to do is implement the effect of WoL inside there.

**Comment by ronancpl** [comment]
Refer to CashShop class line 90 to see how pets are implemented when buying a pet. WoL should use a similar behavior.
