### ISSUE TITLE
Putting the pet into cash inventory while it's currently activated will crash. 

### ISSUE THREAD

**Issue by UltimateMors** [ronancpl/MapleSolaxiaV2#120]
It's-a me again. It's a small bug this time. If you try equipping a pet, going into cash shop, then putting the pet into cash shop, you will crash.

To replicate:

1. Buy a pet.
2. Spawn the pet outside the cash shop.
3. Go back into the cash shop.
4. Put the pet into your cash shop inventory. 
5. Leave the cash shop.

You will crash.

Also, could you add a thing that allows GM's to deactivate hide when re-spawning? It gets extremely irritating after a few re-spawns. I could it but I don't know how to commit. 

This is using the latest version of the source, and thanks for the that tiger fix.

**Comment by ronancpl** [comment]
No problem. Also fixed that pet issue on Cash Shop.

Regarding this deactivating GM hide when respawning, I've figured out that a new table on the SQL would be needed for the solution. Since the source is starting to grow way too much, I would rather refrain from introducing new tables like that just for the GM's convenience. The original idea would be that GM's would always login unnoticed by the players, only showing up if the GM wishes, but to overcome that issue one can simply make the GM always login unhided.
