### ISSUE TITLE
GM hide skill freezes mobs in map

### ISSUE THREAD

**Issue by mrjk611** [ronancpl/MapleSolaxiaV2#124]
Hey ronan,

First off, thank you so much for all your source and your tutorial on how to set it up. 
I am new to this so I apologize in advance.

I set up my v83 private server using your source files and everything works which I am very happy about!

However, I did notice that whenever a gm uses hide skill the mobs in the map will freeze.

I tried using the skill again to unhide then used !reloadmaps -> this made the mobs move again.
But when I use the skill to hide then use !reloadmaps -> the mobs are still frozen.

Also, I noticed that when a gm is in hidden mode (using the hide skill), the mobs can sill damage the character. 

What can I do to fix this issue??

**Comment by ronancpl** [comment]
This is an intentional feature. As long as there is no active players in the area (hidden GMs doesn't count as those), mobs are supposed to remain in "inactive state", hence frozen.

Regarding damaging being dealt, hide doesn't have the same behavior as the invisibility skills such as wind walk or dark sight. It is supposed to not deplet the player's HP, but the physical knockback is supposed to kick in. In order to make it actually work as the reffered skills, search the functions that deals with sending the DARK_SIGHT, WIND_WALK to the player and work it's way through to make the same effect upon GM hide.

**Comment by mrjk611** [comment]
Thank you so much ronan!
I tested the mobs freezing with 2 characters in same map. You were right, it doesn't really affect the mobs as long as another player is in the map while a hidden GM is in the map.

As for the damage, I tried to tweak some codes here and there but had no success. So I'm just going to leave it as is. Thanks for the help.

**Comment by ronancpl** [comment]
No problem.
