### ISSUE TITLE
slow map transitions after entering events

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#55]
any kind of event such as a boat or PQ, after u leave them theres extremely slow map transitions when changing maps

**Comment by ronancpl** [comment]
Didn't experience that. But also, i'm using provided Wz. Another guy got the same slow transition but was using clean v83 Wz.

**Comment by resinate** [comment]
u should team up with someone who knows how to handle packets so you can avoid having to use custom wz mods to get things to work

**Comment by ronancpl** [comment]
Indeed, I should. But that doesn't shrug off inconsistencies that may exist on the very v83 wz files. Instead of doing workarounds all around the server codes to "fix" things up, I chose to change wz as issues arose.

Sadly, that dropped out server/client cohesion for those ppl that wanted to stick/tried to use this server source for their Wzs. For that, I'm terribly sorry.
