### ISSUE TITLE
Monsters can't drop multiple of the same item.

### ISSUE THREAD

**Issue by UltimateMors** [ronancpl/MapleSolaxiaV2#86]
Hello! This source is great and I have been having a lot of fun with using it and messing around with it. Amazing source by all means, however, there's just something that's been bothering the hell out of me. The fact that DropFromMonster does not allow monsters to drop multiple of the same item. I'm not used to how Lithium handles this, but I have just noticed this last night that monsters cannot drop the same item. No matter what, and was wondering if you could fix that? Or, give me a way to fix it. 

Thanks. 

P.S - I'm making a server with this, your credits will be with @ oldstaff command. Haha.

**Comment by ronancpl** [comment]
This is indeed a feature on this server (not capable to drop same itemids). This is due to the data structure being used to hold the drop data informations of the mob.

Peek at db_database.sql, on table definition "temp_data" ("drop_data" too has this structure). They are using PRIMARY KEY (`dropperid`, `itemid`), which maps double keys for the drops. This, followed by INSERT IGNORE all over the sql files will simply ignore any new entry that reuses same <itemid, dropperid> pair. To fix that, you will have to instance a new auto-increment key for the table, since a table MUST have a defined primary key.

Thanks for crediting my name and of the others that have been working on this source, that is most welcome.
