### ISSUE TITLE
Source problems.

### ISSUE THREAD

**Issue by freshmany** [ronancpl/MapleSolaxiaV2#95]
When i first open server. There was no problem at all no character stuck or inventory equipment wipe. After 1 month people getting stuck. Character stuck. Or character wipe. Im sure i done everything correctly?

**Comment by freshmany** [comment]
Im not sure if it the source that has problem or is it me?

**Comment by ronancpl** [comment]
To start a point: no sources comes error-free, take that as granted. As you may have read at my thread on RZ, although many aspects of the base source would have been fixed, it was claimed that this source would still have many issues that have not been patched yet. To make it to production for a full-fledged private server many more fixes would still be needed.

As a matter of fact, the stakes are high on that NO source of a project as large as MapleStory can be deemed "complete" altogether, as these things must be extensively tested & treated before setting up a server for the public. Even after publishing it (server made online), most probably there will be problems on the source of the server that must be treated and assimilated to the online server via "periodic maintenance schedules".

Long story short: yes, this source does have many problems (well, every source has). If one wants to make the server online to the public, they must be committed in debugging what is going on the server system they have and find a solution for that.

Now, regarding this character stuck/character wipe/npc on random positions. If you refer to Solaxia "last debugging activities before shutdown", they were on the process on debugging TimerManager, that would be dropping NullPointerExceptions after some period of server activity. The TimerManager is a core mechanic for this server, and the issue troubleshooting for it is still pending (debug it would involve some hours of activity to try to find the bug, I didn't even bother to try for it). My advice is to start by debugging what is going on with the TimerManager, as this problem is probably the one that is giving all that randomness to your server.

**Comment by freshmany** [comment]
So timemanager.java yes? =)

**Comment by tienvtran89** [comment]
Try use MoopleDev MapleClient disconnect . 
I fixed it. Probaby problem in disconnect

**Comment by freshmany** [comment]
tran u vietnamese? i can tell -
can u please help me?
i want to fix this =[

so i download moopledev then i take mapleclient.java???

**Comment by tienvtran89** [comment]
Yes im Vietnamese. Try take disconnect in mapleclient.

**Comment by freshmany** [comment]
anh oi can u post it for me here and i just copy replace?

**Comment by freshmany** [comment]
you have facebook skype that i can add you?

**Comment by tienvtran89** [comment]
Email me tienvtran89@gmail.com.
